prvi pull request
pfe-rs/izvestaji pull request #6
Opened 2022-10-10 20:38 UTC by NovakTJ

2022-10-12 11:46 UTC, KockaAdmiralac requested changes
Komentari na prvu verziju, svakako znate šta još treba da dodate.

2022-10-12 11:46 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Daisy deskriptor je algoritam koji pretvara lokalne regione slike u niskodimenzionalne invarijantne deskriptore koji mogu da se koriste za uparivanje i klasifikaciju.
Deskriptor je, koliko znam, struktura podataka, ne algoritam.

2022-10-12 11:46 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Postoje 4 glavna parametra koji određuju izgled DAISY deskriptora: prečnik oblasti komšija(R), broj izdvojenih orijentacija(o), broj konvolucionih orijentacionih prstenova(r), broj krugova na svakom
LaTeX.
```suggestion
Postoje 4 glavna parametra koji određuju izgled DAISY deskriptora: prečnik oblasti komšija ($R$), broj izdvojenih orijentacija ($o$), broj konvolucionih orijentacionih prstenova ($r$), broj krugova na svakom prstenu ($c$)
```

2022-10-12 11:46 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Uspešnost algoritma je merena na osnovu dve metrike: srednja greška i procenat pogrešnih piksela. Srednja greška je računata kao srednja vrednost zbira kvadrata razlike komponenata istinotog vektora
Slovna greška.
```suggestion
Uspešnost algoritma je merena na osnovu dve metrike: srednja greška i procenat pogrešnih piksela. Srednja greška je računata kao srednja vrednost zbira kvadrata razlike komponenata istinitog vektora pomeraja i naše procene. Pogrešan piksel se smatra onaj čija je greska veća od 3 piksela. Za evaluaciju su korišćeni podaci iz KITTI baze koja sadrži parove uzastopnih slika sa primerima manjih i većih pomeraja. Svaki par slika u skupu za trening sadrži i istinito polje pokreta.
```

2022-10-12 11:46 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Tabela prikazuje zavisnost metrike od broja izvršenih BCD-ova. Testiranja su vršena nad skupom od po sedam parova slika.
Koliko je bilo vreme izvršavanja? Je l' možemo da probamo ovo nad celom bazom (400 parova) i koliko bi bilo potrebno vremena? Je l' još uvek imate odvojene rezultate ovih BCD-ova ili samo ove prosečne?

2022-10-12 11:46 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +| BCD      | Srednja greska | Procenat pogrešnih piksela|
Slovna greška.
```suggestion
| BCD      | Srednja greška | Procenat pogrešnih piksela|
```

2022-10-15 10:46 UTC, NovakTJ commented on content/2022/estimacija-pokreta.md
> +Ciljana slika se deli  na ćelije jednakih veličina. Za svaku ćeliju se primenjuje randomizovana k-d šuma na deskriptore piksela, računanih DAISY algoritmom, koji pripadaju toj ćeliji, stvarajući efik
Zadrzaćemo naziv šuma, to je konkretan korišćen algoritam

2022-10-15 13:38 UTC, NovakTJ commented on content/2022/estimacija-pokreta.md
> +Kako susedni pikseli često imaju sličan vektor protoka, dodatno se uzima N nasumičnih piksela iz lokalne Gausove distribucije centrirane na referentnom pikselu i dodaju se pikseli koji najbolje odgov
Ovaj deo je promenjen

2022-11-09 18:31 UTC, bojana0507 commented on content/2022/estimacija-pokreta.md
> +Većina metoda definiše problem estimacije kao problem minimizacije energije.
Ovo se moze spojiti u isti pasus sa pasusom iznad i ispod

2022-11-10 10:37 UTC, KockaAdmiralac requested changes
Komentari na drugu verziju predloga. @bojana0507 ispravi me ako sam nešto zaboravio.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Drugi sabirak se ne računa grubom silom, već pomoću *k-skupova*.
Izbeći termin "gruba sila".

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +### K-skupovi
Nije jasno da je ovo termin iz referentnog rada, nekome može da izgleda kao [termin iz geometrije](https://en.wikipedia.org/wiki/K-set_(geometry)). Umesto samo promene slova razmislio bih kako ovo napisati da se zna da se ovo odnosi baš na skupove definisane jednačinom ispod.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +$$
Popraviti jednačinu.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Iako deluje da mogu biti od pomoći, u originalnom radu je pokazano da korišćenje algoritama detekcije ivica u ovom delu programa daje gore rezultate, tako da nisu korišćeni.
Ovaj pasus nema veze sa k-skupovima, pomeriti na neko drugo mesto.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Algoritam kreće od početka reda piksela, i u $\mathbf{C}(x, l)$ čuva najmanju od kumulativnih cena svih kombinacija u delu reda od početnog do piksela rednog broja $x$, koje se završavaju predlogom $
```suggestion
Algoritam kreće od početka reda piksela, i u $\mathbf{C}(x, l)$ čuva najmanju od kumulativnih cena svih kombinacija u delu reda od početnog do piksela rednog broja $x$, koje se završavaju predlogom $l$ tog piksela. Predlozi označeni sa $l_{x, y}^*$ su trenutni predlozi iz susednih redova na lokaciji $(x,y)$, a $L(x)$ skup predloga piksela $x$. Sami vektori protoka koji sačinjavaju tu kombinaciju se ne čuvaju, već se najbolja kombinacija rekonstruiše idući unazad kroz matricu nakon što se popuni do kraja. Stari predlozi vektora se zamene novim i kreće se sa obradom sledećeg reda.
```

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +### K-skupovi
Pošto se k-skupovi koriste prilikom pronalaženja optimalnih vektora, mislim da ovde fali još jedan #.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +$$
Mislim da smo pričali da ove jednačine treba bolje objasniti.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +(Malo o bazi)
Dodati ovo.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +### Postprocesiranje
Dodati ovo.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Uspešnost algoritma je merena na osnovu dve metrike: srednja greška i procenat pogrešnih piksela. Srednja greška je računata kao srednja vrednost zbira kvadrata razlike komponenata istinitog vektora
Referenca na KITTI.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +![Ppp](/images/2022/estimacija-pokreta/b.svg)
Molim vas da u alternativnom tekstu napišete opis slike koji bi imao smisla osobama koje ne mogu da vide sliku, i takođe da imena fajlova budu smislena.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +![Ppp](/images/2022/estimacija-pokreta/b.svg)
Pomenuli smo da za procenat pogrešnih piksela ne moramo praviti grafik, već samo za srednju grešku.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +| 0      | 13.81       |   30.97 |
Rekli smo da na ovom mestu treba dodati merne nesigurnosti, za sve vrednosti koje su usrednjene treba izračunati standardnu devijaciju i zabeležiti pored srednje vrednosti, i uskladiti broj cifara srednje vrednosti sa brojem cifara greške. U moje vreme, Stojke bi nas linkovao do [ove prezentacije](https://web.archive.org/web/20181024021947im_/http://fiz.petnica.rs/wp-content/uploads/2013/05/Obrada_rezultata.pdf), koja vam i sad može biti od koristi.

2022-11-10 10:37 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +![Srednja greska](/images/2022/estimacija-pokreta/a.svg)
Kad ovo budete ponovo izračunavali, dodajte i _error bar_.

2022-11-11 20:43 UTC, NovakTJ commented on content/2022/estimacija-pokreta.md
> +Ciljana slika se deli na ćelije jednakih veličina. Za svaku ćeliju se koristi nasumična k-d šuma (eng: *randomized k-d tree forest*) za deskriptore piksela koji pripadaju toj ćeliji. To je efikasna s
dodao sam referencu za flann, tu je objasnjen algoritam k d sume. to je svakako poznat algoritam, nisam siguran odakle bih ga citirao

2022-11-11 20:58 UTC, NovakTJ commented on content/2022/estimacija-pokreta.md
> +Ciljana slika se deli na ćelije jednakih veličina. Za svaku ćeliju se koristi nasumična k-d šuma (eng: *randomized k-d tree forest*) za deskriptore piksela koji pripadaju toj ćeliji. To je efikasna s
objasnio detaljnije i dodao sta su okolne celije

2022-11-11 21:01 UTC, NovakTJ commented on content/2022/estimacija-pokreta.md
> +Polje protoka je modelirano kao Markovljev slučajni proces. Problem procene pokreta je sveden na minimizaciju zbira cena vektora protoka i cena slaganja.
i ovo je generalan koncept iz statistike, šta bih mogao da citiram? referentni rad nije citirao nikoga kada je pominjao conditional random field.

2022-11-11 21:06 UTC, NovakTJ commented on content/2022/estimacija-pokreta.md
> +U svakom trenutku se čuva trenutno polje protoka, i ukupna cena se postepeno smanjuje odabirom bolje kombinacije vektora protoka iz skupa vektora svakog piksela. To se radi pomoću spuštanja po blokov
da, tako sam i ja razumeo. spušta se po blokovima koordinata, a ne samo po jednoj koordinati, pa sam tako i preveo. da li je nejasno iz prevoda?

2022-11-11 21:07 UTC, NovakTJ commented on content/2022/estimacija-pokreta.md
> +Problem minimizacije je rešen dinamičkom matricom $C$, čije su koordinate pozicija piksela u redu i redni broj trenutnog predloga u tom pikselu. Matrica se popunjava po jednačini:
da li je sad bolje?

2022-11-12 09:50 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +U svakom trenutku se čuva trenutno polje protoka, i ukupna cena se postepeno smanjuje odabirom bolje kombinacije vektora protoka iz skupa vektora svakog piksela. To se radi pomoću spuštanja po blokov
> [...] nalaženjem minimalnog zbira cena u **pojedinačnom** redu ili koloni piksela na slici.

Ako se spuštamo po **blokovima** koordinata, a minimalni zbir cena nalazimo u **pojedinačnom** redu ili koloni piksela, šta je onda tu "blok"?

2022-11-12 09:58 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Problem minimizacije je rešen dinamičkom matricom $C$, čije su koordinate pozicija piksela u redu i redni broj trenutnog predloga u tom pikselu. Matrica se popunjava po jednačini:
Dinamičko programiranje nije algoritam. Ali možeš da kažeš "Za red $y$ se matrica dinamičkim programiranjem..."

2022-11-12 10:01 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Ciljana slika se deli na ćelije visine $h$ i širine $w$. Svaki piksel referentne slike treba dobiti po $K$ predloga destinacije vektora protoka iz svake okolne ćelije ciljane slike, čime se dobija ra
Pošto su ovo matematičke jednačine, nema potrebe za znakom puta na ovom mestu. Takođe, znak puta se piše sa `\cdot` obično, $*$ može eventualno konvolucija da bude.
```suggestion
Ciljana slika se deli na ćelije visine $h$ i širine $w$. Svaki piksel referentne slike treba dobiti po $K$ predloga destinacije vektora protoka iz svake okolne ćelije ciljane slike, čime se dobija raznovrstan skup predloga od kojih će se kasnije birati konačni vektor protoka. Okolne ćelije definišemo kao ćelije u pravougaoniku širine $5w$ i visine $5h$, centriranom na referentnoj ćeliji. Za svaku ćeliju se koristi nasumična k-d šuma (eng: *randomized k-d tree forest*) za deskriptore piksela koji pripadaju toj ćeliji. To je efikasna struktura za nalaženje $K$ piksela najbližih datom pikselu, po sličnosti deskriptora računatih DAISY algoritmom. Za razliku od referentne metode koja čuva sve k-d šume tokom generisanja predloga, naša metoda pravi k-d šumu za jednu ćeliju, iskoristi je za nalaženje najsličnijih piksela u ćelijama u okolini i više je ne čuva. Za pravljenje k-d šuma koristi se algoritam iz biblioteke FLANN[^10].
```

2022-11-12 13:38 UTC, NovakTJ commented on content/2022/estimacija-pokreta.md
> +U svakom trenutku se čuva trenutno polje protoka, i ukupna cena se postepeno smanjuje odabirom bolje kombinacije vektora protoka iz skupa vektora svakog piksela. To se radi pomoću spuštanja po blokov
funkcija cene se gleda kao funkcija ciji su argumenti sve labele odabranih predloga. ako sam dobro shvatio, spustanje po pojedinacnim koordinatama bi bilo da menjamo izabrani vektor za piksel po piksel (trazeci minimum njegove cene vektora i 4 cene slaganja oko njega), a posto nalazimo minimum za ceo red ili kolonu to je blok koordinata. da li da objasnim ovo i u tekstu?

2022-11-13 19:06 UTC, KockaAdmiralac requested changes
Komentari na treću verziju, nakon što svi odeljci popunjeni i reference uglavnom dodate.

2022-11-13 19:06 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Ranije opisani algoritam dodeljuje svaki piksel referentne slike pikselu ciljane slike. Kao unapređenje algoritma vrši se izbacivanje piksela na osnovu dva kriterijuma: provere konzistentnosti i ukla
Predložene izmene radi čitljivosti.
```suggestion
Ranije opisani algoritam dodeljuje svaki piksel referentne slike pikselu ciljane slike. Kao unapređenje algoritma vrši se izbacivanje piksela na osnovu dva kriterijuma: provere konzistentnosti i uklanjanja malih segmenata, nakon čega se primenjuje EpicFlow.[^11]

Provera konzistentnosti se vrši tako što se računa optički protok unapred, kao i unazad, u suprotnom poretku od datog u bazi podataka, i vektor protoka se izbacuje ako je njegovo odstupanje veće od definisanog praga. Zatim se izbacuju mali segmenti od najviše 100 piksela koji odstupaju od kretanja okolnih piksela usled pretpostavke da se radi o kretanju većih celina i da izolovani segmenti odgovaraju pogrešnoj proceni.

Kako bi se dobilo u potpunosti definisano polje protoka koristi se EpicFlow algoritam, koji pikselima koji nemaju definisan protok računa isti, uzimajući u obzir okolne piksele i ivice slike. EpicFlow kreće od hipoteze da ivice slike definišu granice kretanja, odnosno da pikseli sa suprotne strane ivice odgovaraju kretaju različitih objekata.
```

2022-11-13 19:06 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Roth, S., Black, M.J.: On the spatial statistics of optical flow. IJCV 74(1), 33–50 (2007)
> Roth, S., Black, M.J.: On the spatial statistics of optical flow. IJCV 74(1), 33–50 (2007)

Šta se dešava sa ovim redom, deluje da samo lebdi ovde.

2022-11-13 23:33 UTC, bojana0507 commented on content/2022/estimacija-pokreta.md
> +Za evaluaciju programa korisćena je KITTI[^12] baza za optički protok. Podaci su usnimljeni u Karlsrueru, gradu u Nemačkoj. Baza se sastoji iz 200 scena u trening setu i 200 scena u test setu. Svaka
Dve sekvence ispada vise od dve slike, preformulisati samo u tipa "iz dve uzastopno uslikane slike, gde je jedna referentna, a druga ciljana" ili "iz sekvence koju cine dve uzastopno zabelezene slike, referentna i ciljana".

2022-11-13 23:37 UTC, bojana0507 commented on content/2022/estimacija-pokreta.md
> +Ranije opisani algoritam dodeljuje svaki piksel referentne slike pikselu ciljane slike. Kao unapređenje algoritma vrši se izbacivanje piksela na osnovu dva kriterijuma: provere konzistentnosti i ukla
```suggestion
Ranije opisani algoritam dodeljuje svaki piksel referentne slike pikselu ciljane slike. Kao unapređenje algoritma vrši se izbacivanje piksela na osnovu dva kriterijuma: provere konzistentnosti i uklanjanja malih segmenata, nakon čega se primenjuje EpicFlow[^13]. 

Provera konzistentnosti se vrši tako što se računa optički protok unapred kao i unazad, u suprotnom poretku od datog u bazi podataka i vektor protoka se izbacuje ako je odstupanje vektora protoka veće od definisanog praga. Zatim se izbacuju mali segmenti od najviše 100 piksela koji odstupaju od kretanja okolnih piksela usled pretpostavke da se radi o kretanju većih celina i da izolovani segmenti odgovaraju pogrešnoj proceni. 

Kako bi se dobilo u potpunosti definisano polje protoka koristi se EpicFlow algoritam koji pikselima koji nemaju definisan protok računa isti uzimajući u obzir okolne piksele i ivice slike sa hipotezom da ivice slike definišu granice kretanja, odnosno da pikseli sa suprotne strane ivice odgovaraju kretanju različitih objekata.
```

2022-11-13 23:39 UTC, bojana0507 commented on content/2022/estimacija-pokreta.md
> +Ranije opisani algoritam dodeljuje svaki piksel referentne slike pikselu ciljane slike. Kao unapređenje algoritma vrši se izbacivanje piksela na osnovu dva kriterijuma: provere konzistentnosti i ukla
Takodje, mozda i za procenat nepoklapanja koji je granica za odbacivanje i broj piksela koji je granica za malu grupu, uvesti neke dve oznake, pa na kraju gde pisu vrednosti ostalih parametara, napisati i te? Ili ako ne, onda bar ovde dodati granicu i za procenat nepoklapanja vrednost kad vec ima za broj piksela male grupe.

2022-11-13 23:44 UTC, bojana0507 commented on content/2022/estimacija-pokreta.md
> +[^13]: Revaud, J., Weinzaepfel, P., Harchaoui, Z., & Schmid, C. (2015). Epicflow: Edge-preserving interpolation of correspondences for optical flow. In Proceedings of the IEEE conference on computer
fali negde kao dodatni odeljak o kom smo pricali za izabrane vrednosti svih pomenutih parametara, kao sto su oni imali onaj dodatan dokument u ref. radu, da bi neko mogao da rekonstruise

2022-11-13 23:54 UTC, KockaAdmiralac reviewed
Dve stvari koje sam zaboravio.

2022-11-13 23:54 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +
Zaboravio sam ranije da pomenem ali na ovom mestu fale apstrakt i grafički apstrakt, obavezno dodati do kraja sledeće nedelje.

2022-11-13 23:54 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +
Na ovom mestu fali zaključak kada ga budete imali, dodati nakon rezultata.

2022-11-21 01:16 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +U radu se vrši određivanje potpunog polja protoka diskretnim pristupom uz korišćenje tri optimizacione metode koje omogućavaju smanjenje potrebnih računskih i memorijskih resursa. Njihovo korišćenje
Srpski termini.
```suggestion
U radu se vrši određivanje potpunog polja protoka diskretnim pristupom uz korišćenje tri optimizacione metode koje omogućavaju smanjenje potrebnih računskih i memorijskih resursa. Njihovo korišćenje dozvoljava procenu optičkog protoka velikih pomeraja. Problem optičkog protoka se svodi na pronalaženje parova piksela referentne i ciljane slike na osnovu nekog parametra, u ovom radu sličnosti njihovih DAISY deskriptora. Prvi način optimizacije koji je korišćen u radu je ograničenje skupa predloga na fiksan broj. Predlozi se pronalaze korišćenjem algoritma nasumične k-d šume. Drugi način jeste korišćenje spuštanja po blokovima koordinata za pronalaženje optimalnih kombinacija usaglašenih vektora protoka iz skupa predloga. Treći vid optimizacije je korišćenje skupova sličnih predloga prilikom obrade predloga susednih piksela. Procenjeno polje se unapređuje postprocesiranjem i izbačeni vektori se ponovo računaju interpolacijom korišćenjem EpicFlow algoritma. Rezultati su dobijeni evaluacijom nad KITTI bazom podataka.
```

2022-11-23 22:09 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Provera konzistentnosti se vrši tako što se računa optički protok unapred kao i unazad, u suprotnom poretku od datog u bazi podataka i vektor protoka se izbacuje ako je odstupanje vektora protoka već
Predlažem ponovo svoje izmene radi čitljivosti, kako bih razrešio prethodni neažurni komentar na tu temu.
```suggestion
Provera konzistentnosti se vrši tako što se računa optički protok unapred, kao i unazad, u suprotnom poretku od datog u bazi podataka, i vektor protoka se izbacuje ako je njegovo odstupanje veće od definisanog praga. Zatim se izbacuju mali segmenti od najviše 100 piksela koji odstupaju od kretanja okolnih piksela usled pretpostavke da se radi o kretanju većih celina i da izolovani segmenti odgovaraju pogrešnoj proceni.
```

2022-11-23 22:11 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Kako bi se dobilo u potpunosti definisano polje protoka koristi se EpicFlow algoritam koji pikselima koji nemaju definisan protok računa isti uzimajući u obzir okolne piksele i ivice slike sa hipotez
Isto kao iznad.
```suggestion
Kako bi se dobilo u potpunosti definisano polje protoka koristi se EpicFlow algoritam, koji pikselima koji nemaju definisan protok računa isti, uzimajući u obzir okolne piksele i ivice slike. EpicFlow kreće od hipoteze da ivice slike definišu granice kretanja, odnosno da pikseli sa suprotne strane ivice odgovaraju kretaju različitih objekata.
```

2022-11-23 22:13 UTC, KockaAdmiralac commented on content/2022/estimacija-pokreta.md
> +Sledeći primere iz *stereo matching*-a optimizacija energija se može olakšati korišćenjem diskretnih optimizacionih algoritama , poput *graph cut*-ova[^6] ili *message passing*[^7] koje su često bile
Izmene u zapetama.
```suggestion
Sledeći primere iz *stereo matching*-a, optimizacija energija se može olakšati korišćenjem diskretnih optimizacionih algoritama, poput *graph cut*-ova[^6] ili *message passing*[^7] koje su često bile u mogućnosti da ostvare približno globalan optimum. Iako se estimacija dispariteta može posmatrati i kao ograničeni slučaj optičkog protoka, malo autora je pokušalo da koristi diskretnu optimizaciju za estimaciju optičkog protoka.
```

2025-06-28 19:18 UTC, merged